# Source: https://github.com/mirzaim/cuda-devcontainer/blob/main/.devcontainer/Dockerfile

ARG VARIANT="ubuntu24.04" 
ARG CUDA_VERSION="12.8.0"
FROM nvidia/cuda:${CUDA_VERSION}-cudnn-devel-${VARIANT}


# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>